name: Auto Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          java-package: jdk
          architecture: x64
      - run: mvn -B package --file pom.xml --debug --errors
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: actions/upload-artifact@v2
        with:
          name: SoulJars.jar
          path: staging
